import type { AnalysisResult } from './types';
import jsPDF from 'jspdf';

export async function exportResultPdf(result: AnalysisResult, imagePreview?: string): Promise<void> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  // ── Header ──
  doc.setFillColor(14, 27, 44);
  doc.rect(0, 0, pageWidth, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('OsteoScreen', margin, 12);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(200, 230, 232);
  doc.text('Clinical Decision Support Report — NOT A MEDICAL DIAGNOSIS', margin, 20);
  doc.setTextColor(150, 180, 182);
  doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth - margin, 20, { align: 'right' });
  y = 40;

  // ── Risk Badge ──
  const riskColor: Record<string, [number,number,number]> = {
    low:      [45, 167, 113],
    moderate: [245, 166, 35],
    high:     [238, 106, 95],
  };
  const [r, g, b] = riskColor[result.risk_level] ?? [100, 100, 100];
  doc.setFillColor(r, g, b);
  doc.roundedRect(margin, y, 60, 14, 3, 3, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  const riskLabel = result.risk_level === 'high' ? 'ELEVATED RISK' :
                    result.risk_level === 'moderate' ? 'MODERATE RISK' : 'LOW RISK';
  doc.text(riskLabel, margin + 30, y + 9, { align: 'center' });

  doc.setTextColor(90, 99, 118);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Confidence: ${(result.confidence * 100).toFixed(1)}%`, margin + 70, y + 9);
  y += 22;

  // ── Key Metrics ──
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(14, 27, 44);
  doc.text('Key Bone Mineral Density Metrics', margin, y);
  y += 6;
  doc.setDrawColor(220, 226, 234);
  doc.line(margin, y, margin + contentWidth, y);
  y += 6;

  const metrics = [
    ['T-Score',           String(result.metrics.t_score)],
    ['BMD Estimate',      `${result.metrics.bmd_estimate_gcm2} g/cm²`],
    ['WHO Classification',result.metrics.who_classification],
    ['Scan Quality',      result.metrics.scan_quality],
    ['Model Version',     result.metrics.model_version],
  ];

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  metrics.forEach(([key, val], i) => {
    const xKey = margin + (i % 2 === 0 ? 0 : contentWidth / 2);
    const xVal = xKey + 48;
    if (i % 2 === 0 && i > 0) y += 8;
    doc.setTextColor(90, 99, 118);
    doc.text(key + ':', xKey, y);
    doc.setTextColor(14, 27, 44);
    doc.setFont('helvetica', 'bold');
    doc.text(val, xVal, y);
    doc.setFont('helvetica', 'normal');
    if (i % 2 === 1 || i === metrics.length - 1) y += 8;
  });
  y += 4;

  if (imagePreview) {
    try {
      const imgData = await loadImageAsDataUrl(imagePreview);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(14, 27, 44);
      doc.text('Scan Preview', margin, y);
      y += 6;
      doc.addImage(imgData, 'PNG', margin, y, 60, 60, undefined, 'FAST');
      y += 68;
    } catch (error) {
      console.warn('Failed to embed preview image in PDF', error);
    }
  }

  // ── Interpretation ──
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(14, 27, 44);
  doc.text('Clinical Interpretation', margin, y);
  y += 6;
  doc.setDrawColor(220, 226, 234);
  doc.line(margin, y, margin + contentWidth, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(44, 55, 72);
  const interpretLines = doc.splitTextToSize(result.interpretation, contentWidth);
  doc.text(interpretLines, margin, y);
  y += interpretLines.length * 5 + 6;

  // ── Next Steps ──
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(14, 27, 44);
  doc.text('Recommended Next Steps', margin, y);
  y += 6;
  doc.setDrawColor(220, 226, 234);
  doc.line(margin, y, margin + contentWidth, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(44, 55, 72);
  result.next_steps.forEach((step) => {
    doc.setFillColor(28, 156, 167);
    doc.circle(margin + 2, y - 1.5, 1.2, 'F');
    const stepLines = doc.splitTextToSize(step, contentWidth - 8);
    doc.text(stepLines, margin + 7, y);
    y += stepLines.length * 5 + 3;
  });
  y += 4;

  // ── Disclaimer ──
  if (y > 240) { doc.addPage(); y = 20; }
  doc.setFillColor(255, 245, 245);
  doc.setDrawColor(238, 106, 95);
  doc.roundedRect(margin, y, contentWidth, 30, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(192, 57, 43);
  doc.text('⚠ Important Disclaimer', margin + 4, y + 7);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(80, 40, 40);
  const discText =
    'This report is generated by an AI model for research and decision-support purposes only. ' +
    'It does not constitute a medical diagnosis and must not replace professional clinical judgment. ' +
    'Model outputs are probabilistic and may be inaccurate. Consult a licensed healthcare provider for all medical decisions. ' +
    'If you experience acute pain, trauma, or red-flag symptoms, seek immediate medical care.';
  const discLines = doc.splitTextToSize(discText, contentWidth - 8);
  doc.text(discLines, margin + 4, y + 14);

  doc.save(`OsteoScreen_Report_${Date.now()}.pdf`);
}

async function loadImageAsDataUrl(src: string): Promise<string> {
  const response = await fetch(src);
  const blob = await response.blob();

  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      if (typeof reader.result === 'string') {
        resolve(reader.result);
      } else {
        reject(new Error('Failed to convert preview to base64 string.'));
      }
    };
    reader.onerror = () => reject(new Error('Failed to read preview blob.'));
    reader.readAsDataURL(blob);
  });
}
